# name: Deploy to Vercel (Multi-Env)

# on:
#   push:
#     branches:
#       - develop
#       - release
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     env:
#       NODE_ENV: production

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test --if-present

#       - name: Build project
#         run: npm run build

#       # Define o ambiente com base na branch
#       - name: Set environment variables
#         id: env-setup
#         run: |
#           if [[ "${GITHUB_REF##*/}" == "main" ]]; then
#             echo "env=production" >> $GITHUB_OUTPUT
#             echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID_PROD }}" >> $GITHUB_ENV
#             echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_PROD }}" >> $GITHUB_ENV
#             echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN_PROD }}" >> $GITHUB_ENV
#           elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
#             echo "env=staging" >> $GITHUB_OUTPUT
#             echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID_STG }}" >> $GITHUB_ENV
#             echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_STG }}" >> $GITHUB_ENV
#             echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN_STG }}" >> $GITHUB_ENV
#           else
#             echo "env=development" >> $GITHUB_OUTPUT
#             echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID_DEV }}" >> $GITHUB_ENV
#             echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_DEV }}" >> $GITHUB_ENV
#             echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN_DEV }}" >> $GITHUB_ENV
#           fi

#       - name: Deploy to Vercel
#         uses: amondnet/vercel-action@v25
#         with:
#           vercel-token: ${{ env.VERCEL_TOKEN }}
#           vercel-org-id: ${{ env.VERCEL_ORG_ID }}
#           vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
#           working-directory: ./
#           prod: ${{ github.ref == 'refs/heads/main' }}
